name: Matrix Demo
on:
  push:
    branches:
      - main
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version : [12,14]
        operating-system: [ubuntu-latest,windows-latest]
    name: Build project
    runs-on: $ {{ matrix.operating-system }}
    steps:
      # Here an action is used to get code from repository into the runner
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node Js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.operating-system }}
      - name: Install dependencies
        run: npm ci


